package web

// Code in this file is the single source of truth for the local REST API's
// machine-readable description. openapi_catalogue_test.go scans the package's
// own route registrations and fails when a registered /api route is missing
// here, so the generated OpenAPI document and the browsable reference page
// cannot drift away from the routes the server actually serves.

// localAPICatalogue returns every documented local API operation, grouped in
// presentation order.
func localAPICatalogue() []localAPIOperation {
	return []localAPIOperation{
		{Group: "Documentation", Method: "GET", Path: "/api/docs", Summary: "Open the browsable local API reference"},
		{Group: "Documentation", Method: "GET", Path: "/api/openapi.json", Summary: "Read this OpenAPI document"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs", Summary: "List jobs with their legacy status and configuration summary"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs", Summary: "Create and queue a validated job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/validate", Summary: "Validate a job configuration without queueing it"},
		{Group: "Jobs", Method: "DELETE", Path: "/api/v1/jobs/{id}", Summary: "Delete a job and its registered artifacts"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}", Summary: "Read one job and its immutable configuration snapshot"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/archive", Summary: "Archive a finished job out of the active list"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/benchmark", Summary: "Read throughput benchmark figures for a job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/benchmark/snapshot", Summary: "Capture a benchmark snapshot for a job"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/campaign", Summary: "Read the campaign a job belongs to"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/cancel", Summary: "Cancel a job and retain committed results"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/checkpoint", Summary: "Read the durable resume checkpoint of a job"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/collection-plan", Summary: "Read the planned query and cell collection for a job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/concurrency", Summary: "Change the concurrency of a running job"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/coverage", Summary: "Read grid coverage and blind spots for a job"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/download", Summary: "Download the compatible per-job CSV"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/duplicate", Summary: "Duplicate a job configuration into a new draft"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/events", Summary: "Stream lifecycle events as SSE with durable event IDs"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/labels", Summary: "Replace the labels applied to a job"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/logs", Summary: "Download the job log"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/notes", Summary: "Save operator notes on a job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/pause", Summary: "Pause a job at the next safe worker boundary"},
		{Group: "Jobs", Method: "GET", Path: "/api/v1/jobs/{id}/progress", Summary: "Read live progress counters and the current stage"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/proxy-pool", Summary: "Switch the proxy pool a running job uses"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/rename", Summary: "Rename a job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/rerun", Summary: "Rerun a job with the same configuration"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/restart", Summary: "Restart a job from the beginning"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/results/import", Summary: "Import a CSV of results into a job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/resume", Summary: "Resume a paused job from its checkpoint"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/retry", Summary: "Retry a job from the beginning"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/retry-current", Summary: "Retry only the task a job is currently stuck on"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/runtime", Summary: "Change the remaining runtime budget of a running job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/start", Summary: "Start a draft or queued job"},
		{Group: "Jobs", Method: "POST", Path: "/api/v1/jobs/{id}/template", Summary: "Save a job configuration as a reusable template"},
		{Group: "Results", Method: "GET", Path: "/api/v1/results", Summary: "Search, filter, and page normalized businesses"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/bulk", Summary: "Apply a bulk action to a selection of businesses"},
		{Group: "Results", Method: "GET", Path: "/api/v1/results/duplicates", Summary: "List duplicate candidates and their match evidence"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/duplicates/ignore", Summary: "Mark a duplicate pair as not a duplicate"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/duplicates/keep-both", Summary: "Keep both records of a duplicate pair"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/duplicates/merge", Summary: "Merge a duplicate pair into one preferred record"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/enrich", Summary: "Queue website and contact enrichment for a selection"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/lists", Summary: "Create a saved list from a selection"},
		{Group: "Results", Method: "GET", Path: "/api/v1/results/{id}", Summary: "Read one business with provenance and version history"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/{id}/enrich", Summary: "Enrich one business from its website"},
		{Group: "Results", Method: "GET", Path: "/api/v1/results/{id}/enrichment", Summary: "Read stored enrichment evidence for one business"},
		{Group: "Results", Method: "POST", Path: "/api/v1/results/{id}/fields", Summary: "Edit reviewable fields on one business"},
		{Group: "Results", Method: "GET", Path: "/api/v1/results/{id}/quality", Summary: "Read the quality score breakdown for one business"},
		{Group: "Results", Method: "POST", Path: "/api/v1/saved-views", Summary: "Save a named result view with its filters and layout"},
		{Group: "Results", Method: "POST", Path: "/api/v1/saved-views/{id}/delete", Summary: "Delete a saved result view"},
		{Group: "Results", Method: "GET", Path: "/api/v1/search", Summary: "Search jobs, results, and saved objects at once"},
		{Group: "Maps", Method: "GET", Path: "/api/v1/maps/areas", Summary: "List saved map areas"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/areas", Summary: "Save a map area"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/areas/import", Summary: "Import a map area from GeoJSON"},
		{Group: "Maps", Method: "DELETE", Path: "/api/v1/maps/areas/{id}", Summary: "Delete one saved map area"},
		{Group: "Maps", Method: "GET", Path: "/api/v1/maps/areas/{id}", Summary: "Read one saved map area"},
		{Group: "Maps", Method: "PUT", Path: "/api/v1/maps/areas/{id}", Summary: "Replace one saved map area"},
		{Group: "Maps", Method: "GET", Path: "/api/v1/maps/areas/{id}/export", Summary: "Export a saved map area as GeoJSON"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/cells/rescrape", Summary: "Queue selected grid cells for another pass"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/grid/coverage", Summary: "Read per-cell coverage for an area"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/grid/preview", Summary: "Preview the grid cells an area would produce"},
		{Group: "Maps", Method: "GET", Path: "/api/v1/maps/results", Summary: "Read geographic results for the current viewport"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/results", Summary: "Read geographic results for a posted filter"},
		{Group: "Maps", Method: "POST", Path: "/api/v1/maps/results/export", Summary: "Export the geographic result selection"},
		{Group: "Maps", Method: "GET", Path: "/api/v1/maps/tiles/{z}/{x}/{y}", Summary: "Serve a cached OpenStreetMap tile"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxies/test", Summary: "Test a proxy definition before saving it"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxies/{id}/test", Summary: "Test one stored proxy"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxies/{id}/{action}", Summary: "Enable or disable one stored proxy"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxy-pools/import", Summary: "Import a proxy pool from a pasted or uploaded list"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxy-pools/{id}/delete", Summary: "Delete a proxy pool and its members"},
		{Group: "Proxies", Method: "POST", Path: "/api/v1/proxy-pools/{id}/retest-disabled", Summary: "Retest the disabled proxies in a pool"},
		{Group: "Schedules", Method: "POST", Path: "/api/v1/schedules", Summary: "Create a recurring schedule"},
		{Group: "Schedules", Method: "PUT", Path: "/api/v1/schedules/{id}", Summary: "Replace a schedule definition"},
		{Group: "Schedules", Method: "POST", Path: "/api/v1/schedules/{id}/delete", Summary: "Delete a schedule"},
		{Group: "Schedules", Method: "POST", Path: "/api/v1/schedules/{id}/run", Summary: "Run a schedule immediately"},
		{Group: "Schedules", Method: "GET", Path: "/api/v1/schedules/{id}/runs", Summary: "Read the execution history of a schedule"},
		{Group: "Schedules", Method: "POST", Path: "/api/v1/schedules/{id}/update", Summary: "Update a schedule definition"},
		{Group: "Schedules", Method: "POST", Path: "/api/v1/schedules/{id}/{action}", Summary: "Enable or disable a schedule"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/export-profiles", Summary: "List saved export column profiles"},
		{Group: "Exports", Method: "POST", Path: "/api/v1/export-profiles", Summary: "Save an export column profile"},
		{Group: "Exports", Method: "DELETE", Path: "/api/v1/export-profiles/{id}", Summary: "Delete an export column profile"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/export-profiles/{id}", Summary: "Read one export column profile"},
		{Group: "Exports", Method: "POST", Path: "/api/v1/export-profiles/{id}/delete", Summary: "Delete an export column profile"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/exports", Summary: "List export history with counts, sizes, and checksums"},
		{Group: "Exports", Method: "POST", Path: "/api/v1/exports", Summary: "Create an export from all, selected, filtered, or saved-view records"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/exports/presets", Summary: "List saved export presets"},
		{Group: "Exports", Method: "DELETE", Path: "/api/v1/exports/{id}", Summary: "Delete an export and its files"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/exports/{id}", Summary: "Read export status and its verified parts"},
		{Group: "Exports", Method: "POST", Path: "/api/v1/exports/{id}/delete", Summary: "Delete an export and its files"},
		{Group: "Exports", Method: "GET", Path: "/api/v1/exports/{id}/download", Summary: "Download a completed export artifact"},
		{Group: "Exports", Method: "POST", Path: "/api/v1/exports/{id}/repeat", Summary: "Repeat an export with its exact stored configuration"},
		{Group: "Integrations", Method: "GET", Path: "/api/v1/integrations", Summary: "List local delivery destinations"},
		{Group: "Integrations", Method: "POST", Path: "/api/v1/integrations", Summary: "Create a webhook, watch-folder, or local database destination"},
		{Group: "Integrations", Method: "GET", Path: "/api/v1/integrations/deliveries", Summary: "Read delivery history across every destination"},
		{Group: "Integrations", Method: "DELETE", Path: "/api/v1/integrations/{id}", Summary: "Delete one local delivery destination"},
		{Group: "Integrations", Method: "PUT", Path: "/api/v1/integrations/{id}", Summary: "Replace one local delivery destination"},
		{Group: "Integrations", Method: "POST", Path: "/api/v1/integrations/{id}/delete", Summary: "Delete one local delivery destination"},
		{Group: "Integrations", Method: "GET", Path: "/api/v1/integrations/{id}/deliveries", Summary: "Read delivery history for one destination"},
		{Group: "Integrations", Method: "POST", Path: "/api/v1/integrations/{id}/test", Summary: "Send one signed test delivery"},
		{Group: "System", Method: "POST", Path: "/api/v1/onboarding/complete", Summary: "Mark the first-run checklist complete"},
		{Group: "System", Method: "POST", Path: "/api/v1/onboarding/self-test", Summary: "Run the first-run connectivity and capacity checks"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/artifacts/cleanup", Summary: "Delete old unregistered artifacts from a contained directory"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/backups", Summary: "Create a verified local database backup"},
		{Group: "System", Method: "GET", Path: "/api/v1/system/backups/{id}/download", Summary: "Download a verified backup"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/backups/{id}/download", Summary: "Download a backup, decrypting it when a passphrase is supplied"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/backups/{id}/restore", Summary: "Verify a backup and stage it for an offline restore"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/browser-profiles/clear", Summary: "Delete the reusable browser profiles and the site data they hold"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/cache/clear", Summary: "Clear cached map tiles and browser profiles"},
		{Group: "System", Method: "GET", Path: "/api/v1/system/diagnostics/download", Summary: "Download the privacy-scrubbed diagnostics bundle"},
		{Group: "System", Method: "GET", Path: "/api/v1/system/health", Summary: "Read database, workspace, and scheduler health"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/integrity", Summary: "Run a SQLite integrity check"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/jobs/stop-all", Summary: "Request a safe stop for every queued or active job"},
		{Group: "System", Method: "GET", Path: "/api/v1/system/metrics", Summary: "Read CPU, memory, disk, and workspace storage metrics"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/retention/apply", Summary: "Apply the configured retention policies once"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/self-test", Summary: "Run bounded local diagnostics"},
		{Group: "System", Method: "GET", Path: "/api/v1/system/update-info", Summary: "Read offline update and build information"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/vacuum", Summary: "Compact the local database"},
		{Group: "System", Method: "POST", Path: "/api/v1/system/worker/recycle", Summary: "Pause every active job at a safe boundary and resume it from its checkpoint"},
		{Group: "Access", Method: "GET", Path: "/api/v1/api-keys", Summary: "List API-key metadata without any token material"},
		{Group: "Access", Method: "POST", Path: "/api/v1/api-keys", Summary: "Create an API key; the token is returned once"},
		{Group: "Access", Method: "POST", Path: "/api/v1/api-keys/{id}/{action}", Summary: "Enable or disable an API key"},
		{Group: "Access", Method: "GET", Path: "/api/v1/api/request-logs", Summary: "Read recent API request logs with secrets masked"},
		{Group: "Access", Method: "GET", Path: "/api/v1/api/settings", Summary: "Read the local API rate limit"},
		{Group: "Access", Method: "PUT", Path: "/api/v1/api/settings", Summary: "Change the local API rate limit"},
		{Group: "Access", Method: "POST", Path: "/api/v1/security/password", Summary: "Set or change the optional local login password"},
		{Group: "Settings", Method: "POST", Path: "/api/v1/settings", Summary: "Save local application defaults and preferences"},
		{Group: "Local AI", Method: "POST", Path: "/api/v1/ai/assist", Summary: "Run one bounded structured task on the local model"},
		{Group: "Local AI", Method: "GET", Path: "/api/v1/ai/status", Summary: "Check the optional loopback-only Ollama connection"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/business-categories", Summary: "List known Google Business categories"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/category-groups", Summary: "List saved category groups"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/category-groups", Summary: "Save a category group"},
		{Group: "Templates", Method: "DELETE", Path: "/api/v1/category-groups/{id}", Summary: "Delete a category group"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/category-groups/{id}/delete", Summary: "Delete a category group"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/category-groups/{id}/use", Summary: "Record use of a category group"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/keyword-sets", Summary: "List saved keyword sets"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/keyword-sets", Summary: "Save a keyword set"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/keyword-sets/{id}/delete", Summary: "Delete a keyword set"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/keyword-sets/{id}/use", Summary: "Record use of a keyword set"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/scrape-fields", Summary: "List the fields a scrape can collect"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/import", Summary: "Import a scrape template"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/parameters/preview", Summary: "Preview the queries a parameterised template expands to"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/{id}/delete", Summary: "Delete a scrape template"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/{id}/duplicate", Summary: "Duplicate a scrape template"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/templates/{id}/export", Summary: "Export a scrape template"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/{id}/instantiate", Summary: "Create a job draft from a scrape template"},
		{Group: "Templates", Method: "GET", Path: "/api/v1/templates/{id}/metrics", Summary: "Read outcome metrics for a scrape template"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/{id}/pin", Summary: "Pin a scrape template to the top of the list"},
		{Group: "Templates", Method: "POST", Path: "/api/v1/templates/{id}/rename", Summary: "Rename a scrape template"},
		{Group: "Quality", Method: "POST", Path: "/api/v1/quality/recalculate", Summary: "Recalculate quality scores for stored businesses"},
		{Group: "Quality", Method: "GET", Path: "/api/v1/quality/rules", Summary: "Read the local quality scoring rules"},
		{Group: "Quality", Method: "POST", Path: "/api/v1/quality/rules", Summary: "Save the local quality scoring rules"},
		{Group: "Quality", Method: "PUT", Path: "/api/v1/quality/rules", Summary: "Replace the local quality scoring rules"},
		{Group: "Enrichment", Method: "GET", Path: "/api/v1/enrichment/tasks", Summary: "Read queued and completed enrichment tasks"},
		{Group: "Prospects", Method: "GET", Path: "/api/v1/prospects/discovered", Summary: "List discovered prospect companies"},
		{Group: "Prospects", Method: "GET", Path: "/api/v1/prospects/integrations", Summary: "Read the prospect export field mapping"},
		{Group: "Prospects", Method: "PUT", Path: "/api/v1/prospects/integrations", Summary: "Replace the prospect export field mapping"},
		{Group: "Prospects", Method: "GET", Path: "/api/v1/prospects/openers", Summary: "Read the saved prospect opener templates"},
		{Group: "Prospects", Method: "PUT", Path: "/api/v1/prospects/openers", Summary: "Replace the saved prospect opener templates"},
		{Group: "Prospects", Method: "POST", Path: "/api/v1/prospects/queries", Summary: "Generate prospecting queries"},
		{Group: "Prospects", Method: "POST", Path: "/api/v1/prospects/recompute", Summary: "Recompute prospect scores"},
		{Group: "Prospects", Method: "GET", Path: "/api/v1/prospects/scoring", Summary: "Read the prospect scoring configuration"},
		{Group: "Prospects", Method: "PUT", Path: "/api/v1/prospects/scoring", Summary: "Replace the prospect scoring configuration"},
		{Group: "Prospects", Method: "GET", Path: "/api/v1/prospects/summary", Summary: "Read the prospecting summary"},
		{Group: "Dashboard", Method: "GET", Path: "/api/v1/dashboard", Summary: "Read the dashboard aggregate for the local workspace"},
		{Group: "Diagnostics", Method: "GET", Path: "/api/v1/benchmark/compare", Summary: "Compare two benchmark snapshots"},
		{Group: "Diagnostics", Method: "GET", Path: "/api/v1/benchmark/history", Summary: "Read stored throughput benchmark history"},
	}
}
